# Generated by Django 4.1.7 on 2023-03-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('accountNumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('pin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_api.client', unique=True),
        ),
    ]
