# Generated by Django 4.1.7 on 2023-03-07 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('voteCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContestantTitle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titleName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_api.contestant')),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='accountNumber',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='accountNumber',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
        migrations.AddField(
            model_name='contestant',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_api.contestanttitle'),
        ),
    ]
