# Generated by Django 4.1.7 on 2023-03-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0002_contestant_contestanttitle_vote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='contestant',
            new_name='title',
        ),
    ]
