# Generated by Django 4.1.2 on 2023-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0004_rename_lastname_contestant_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='voteCount',
        ),
        migrations.AddField(
            model_name='vote',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
