# Generated by Django 4.1.2 on 2023-03-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0005_remove_contestant_votecount_vote_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestanttitle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
