# Generated by Django 4.1.2 on 2023-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0006_alter_contestanttitle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='count',
        ),
        migrations.AddField(
            model_name='contestant',
            name='voteCount',
            field=models.IntegerField(default=0),
        ),
    ]
