# Generated by Django 4.1.2 on 2023-04-09 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0007_remove_vote_count_contestant_votecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprintID', models.CharField(max_length=3)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
    ]
