# Generated by Django 4.1.2 on 2023-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0008_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='fingerprintID',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
