# Generated by Django 4.1.2 on 2023-04-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0009_alter_voter_fingerprintid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted',
            field=models.CharField(max_length=5),
        ),
    ]
