# Generated by Django 4.1.2 on 2023-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0010_alter_voter_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='fingerprintID',
            field=models.CharField(max_length=3),
        ),
    ]
